getProducts:
  handler: productHandler.getProducts
  events:
    - http:
        path: products
        method: get
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: apiAuthorizer
addProduct:
  handler: productHandler.addProduct
  events:
    - http:
        path: products/new
        method: post
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: apiAuthorizer