addRecipe: 
  handler: recipeHandler.addRecipe
  events:
    - http:
        path: recipes/new
        method: post
        cors: true
        authorizer: 
          type: COGNITO_USER_POOLS
          authorizerId: 
            Ref: apiAuthorizer
getRecipes: 
  handler: recipeHandler.getRecipes
  events:
    - http:
        path: recipes
        method: get
        cors: true
        authorizer: 
          type: COGNITO_USER_POOLS
          authorizerId: 
            Ref: apiAuthorizer
addIngredients: 
  handler: recipeHandler.addIngredients
  events:
    - http:
        path: recipes/{id}/addIngredients
        method: post
        cors: true
        request:
          parameters:
              paths:
                id: true
        authorizer: 
          type: COGNITO_USER_POOLS
          authorizerId: 
            Ref: apiAuthorizer
setIngredients: 
  handler: recipeHandler.setIngredients
  events:
    - http:
        path: recipes/{id}/setIngredients
        method: post
        cors: true
        request:
          parameters:
              paths:
                id: true
        authorizer: 
          type: COGNITO_USER_POOLS
          authorizerId: 
            Ref: apiAuthorizer
setAnalysis: 
  handler: recipeHandler.setAnalysis
  events:
    - http:
        path: recipes/{id}/analysis
        method: post
        cors: true
        request:
          parameters:
              paths:
                id: true
        authorizer: 
          type: COGNITO_USER_POOLS
          authorizerId: 
            Ref: apiAuthorizer
updateRecipe: 
  handler: recipeHandler.updateRecipe
  events:
    - http:
        path: recipes/{id}
        method: patch
        cors: true
        request:
          parameters:
              paths:
                id: true
        authorizer: 
          type: COGNITO_USER_POOLS
          authorizerId: 
            Ref: apiAuthorizer
deleteRecipe: 
  handler: recipeHandler.deleteRecipe
  events:
    - http:
        path: recipes/{id}
        method: delete
        cors: true
        request:
          parameters:
              paths:
                id: true
        authorizer: 
          type: COGNITO_USER_POOLS
          authorizerId: 
            Ref: apiAuthorizer