service: pricer-backend
frameworkVersion: '2'
plugins:
  - serverless-functions-base-path
  - serverless-dynamodb-local
  - serverless-plugin-typescript
  - serverless-offline
custom:
  serverless-offline:
    httpPort: 4000
  functionsBasePath: src/handlers
  dynamodb:
    start:
      migrate: true
    stages:
      - dev
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
      Resource:
        - Fn::GetAtt: 
          - productsTable
          - Arn
        - Fn::GetAtt:
          - unitsTable
          - Arn
        - Fn::GetAtt:
          - recipesTable
          - Arn

resources: '${file(resources.yml)}'
functions:
  - ${file(endpoints/util.yml)}
  - ${file(endpoints/product.yml)}
  - ${file(endpoints/unit.yml)}
  - ${file(endpoints/recipe.yml)}